Repository sosreport/sos, pull requests merged in 2024-12, with the labels that each got.

#3862 [sunbeam] Forbid pki folder & manifest inclusion
  sos/report/plugins/sunbeam.py
  sos/report/plugins/sunbeam_hypervisor.py
Labels: affects ubuntu, ACK (Ready for merge)

#3863 [selinux] Add "boolean list" option to "semanage" command
  sos/report/plugins/selinux.py
Labels: ACK (Ready for merge), Good First Issue

#3865 [man] List --plugopts variant of -k/--plugin-option
  man/en/sos-report.1
Labels: ACK (Ready for merge)

#3866 [cirrus] Update IncludeOnly to check for all man pages
  .cirrus.yml
Labels: ACK (Ready for merge)

#3868 [ceph_mon] Add json output for 'ceph config dump'
  sos/report/plugins/ceph_mon.py
Labels: Needs second ACK, Needs Review

#3871 [foreman] Update location for deb repo
  tests/test_data/foreman_setup.sh
Labels: ACK (Ready for merge), Needs Review

#3874 [os-net-config] Include the os-net-config logfile
  sos/report/plugins/os_net_config.py
Labels: ACK (Ready for merge)

#3878 [foreman] Obfuscate http_proxy passwords
  sos/report/plugins/foreman.py
Labels: ACK (Ready for merge)

#3869 [kubernetes] add kube-system-log-files option, collect some kubelet files
  sos/report/plugins/kubernetes.py
Labels: ACK (Ready for merge)

#3870 [policies] Fix bug in distro identification
  sos/policies/distros/__init__.py
Labels: ACK (Ready for merge), Good First Issue

#3876 [NetworkManager] Get system-connections files from other locations
  sos/report/plugins/networkmanager.py
Labels: ACK (Ready for merge), Needs Review

#3880 [subscription_manager] Obfuscate proxy password from curl cmdline
  sos/report/plugins/subscription_manager.py
Labels: ACK (Ready for merge)

#3881 [foreman] Obfuscate http_proxy passwords. PR-3878 improvement
  sos/report/plugins/__init__.py
  sos/report/plugins/foreman.py
Labels: ACK (Ready for merge), Needs Review

#3886 [collector] Saltstack transport remote_exec handle stderr like other transports
  sos/collector/transports/saltstack.py
Labels: ACK (Ready for merge)

#3883 [readme] Add badges to repo README
  README.md
Labels: Reviewed/Ready for Merge

#3888 [foreman_installer] collect satellite_metrics.yml
  sos/report/plugins/foreman_installer.py
Labels: Reviewed/Ready for Merge, Kind/RedHat
