Repository sosreport/sos, pull requests merged in 2024-11, with the labels that each got.

#3840 [collect] Fix exception when using collect with batch and password
  man/en/sos-collect.1
  sos/collector/__init__.py
Labels: ACK (Ready for merge), Needs Review

#3707 [process] Add output of 'ps auxfwww'
  sos/report/plugins/process.py
Labels: ACK (Ready for merge)

#3842 [kubernetes] Add support for k8s snap
  sos/report/plugins/kubernetes.py
  sos/report/plugins/microk8s.py
Labels: affects ubuntu, ACK (Ready for merge)

#3854 Fix duplicate-handler-exception in OSError exceptions
  sos/options.py
  sos/report/__init__.py
  sos/report/plugins/__init__.py
Labels: ACK (Ready for merge)

#3857 [processor] Update msr load issue to include focal
  sos/report/plugins/processor.py
Labels: affects ubuntu, Needs Review

#3858 [cirrus] Update to use image_family
  .cirrus.yml
Labels: Needs Review

#3859 [sunbeam] Fix obfuscation for masakari and url
  sos/report/plugins/sunbeam_hypervisor.py
Labels: affects ubuntu, Needs Review
