Repository sosreport/sos, pull requests merged in 2025-01, with the labels that each got.

#3896 [networking] Update predicate to include Debian
  sos/report/plugins/networking.py
Labels: Status/Needs Review

#3901 [ipa] Collect ipa-migrate log file
  sos/report/plugins/ipa.py
Labels: enhancement, Reviewed/Ready for Merge

#3902 [foreman_installer] Collect correct satellite_metrics.yml
  sos/report/plugins/foreman_installer.py
Labels: Reviewed/Ready for Merge

#3909 [microcloud]: Invoke `microcloud status`
  sos/report/plugins/microcloud.py
Labels: Kind/Ubuntu, Reviewed/Ready for Merge
