Repository sosreport/sos, pull requests merged in 2025-06, with the labels that each got.

#4044 [foreman] Collect `/var/lib/foreman/red_hat_inventory` dir list
  sos/report/plugins/foreman.py
Labels: Reviewed/Ready for Merge, Quick Change, Status/Needs Review, Kind/Collection

#4013 [juju] Fix juju agent introspect commands
  sos/report/plugins/juju.py
Labels: Kind/Ubuntu, Reviewed/Ready for Merge, Kind/Collection

#3710 [networking] Capture more networking commands
  sos/report/plugins/networking.py
Labels: Reviewed/Ready for Merge, Kind/Collection

#4053 [policy] Update Debian policy to use /tmp for tmp-dir
  debian/patches/0001-debian-change-tmp-dir-location.patch
  debian/patches/0001-debian-do-not-install-LICENSE-README-AUTHORS.patch
  debian/patches/series
  sos/policies/distros/debian.py
Labels: Kind/Ubuntu, Reviewed/Ready for Merge

#4055 [pkg] Update setup to exclude docs for Debian
  debian/patches/0001-debian-do-not-install-LICENSE-README-AUTHORS.patch
  debian/patches/series
  setup.py
Labels: Kind/Ubuntu, Reviewed/Ready for Merge

#4056 [tftpserver] Add Directory Listing /var/lib/tftpboot
  sos/report/plugins/tftpserver.py
Labels: Reviewed/Ready for Merge, Kind/Collection

#4057 [upload] Fix backtrace when cancelling upload
  sos/upload/__init__.py
Labels: Reviewed/Ready for Merge, Kind/Upload

#4030 [aap_containerized] Add container command
  sos/report/plugins/aap_containerized.py
Labels: Reviewed/Ready for Merge, Kind/Collection

#4062 [component] Grab tmpdir from policy
  sos/component.py
Labels: Reviewed/Ready for Merge, Kind/Bug

#4059 [saltmaster] Obfuscate pillar roots in any path
  sos/report/plugins/saltmaster.py
Labels: Kind/Enhancement, Reviewed/Ready for Merge, Kind/Obfuscation

#4063 [firewalld] Collect runtime and permanent policies
  sos/report/plugins/firewalld.py
Labels: Reviewed/Needs 2nd Ack, Status/Needs Review

#4064 [aap_containerized] collect podman inspect logs
  sos/report/plugins/aap_containerized.py
Labels: Reviewed/Ready for Merge, Kind/Collection
