Repository sosreport/sos, pull requests merged in 2025-04, with the labels that each got.

#3978 [pulseaudio]: Created new plugin for pulseaudio
  sos/report/plugins/pulseaudio.py
  sos/report/plugins/soundcard.py
Labels: Reviewed/Needs 2nd Ack, Kind/New plugin

#3976 [charmed_mysql] Add Charmed MySQL K8s support
  sos/report/plugins/charmed_mysql.py
Labels: Kind/Enhancement, Reviewed/Needs 2nd Ack

#3980 [leapp] Update data collected by leapp plugin for RHEL 10
  sos/report/plugins/leapp.py
Labels: Reviewed/Ready for Merge, Kind/Collection

#3984 [report] Increase column size for plugin options
  sos/report/__init__.py
Labels: Reviewed/Ready for Merge, Kind/Collection

#3979 [redis] Fix path error in redis report collection
  sos/report/plugins/redis.py
Labels: Reviewed/Ready for Merge, Kind/Collection

#3982 [cirrus] Update Fedora testing images
  .cirrus.yml
Labels: Kind/Enhancement, Reviewed/Ready for Merge, Kind/Testing

#3985 Fadump sysfs
  sos/report/plugins/kdump.py
Labels: Reviewed/Ready for Merge, Kind/Collection

#3825 [policies|auth] Move away from deprecated datetime.utcnow
  sos/policies/auth/__init__.py
Labels: Reviewed/Needs 2nd Ack, Status/Needs Review

#3989 [openstack_gnocchi] added missing obfuscation for db connection
  sos/report/plugins/openstack_gnocchi.py
Labels: Reviewed/Needs 2nd Ack, Status/Needs Review, Kind/Obfuscation

#3998 [lustre] Add more OSD values
  sos/report/plugins/lustre.py
Labels: Reviewed/Ready for Merge, Kind/Collection

#3997 [subscription_manager] add facts cmd
  sos/report/plugins/subscription_manager.py
Labels: Reviewed/Ready for Merge, Kind/Collection
