Repository sosreport/sos, pull requests merged in 2025-09, with the labels that each got.

#4105 [plugins] Fixes #4104 - Improved AAP plugins to capture more useful diagnostics
  sos/report/plugins/aap_containerized.py
  sos/report/plugins/aap_controller.py
  sos/report/plugins/aap_eda.py
  sos/report/plugins/aap_gateway.py
  sos/report/plugins/aap_hub.py
Labels: Kind/Enhancement, Reviewed/Ready for Merge, Kind/Collection

#4112 [podman] collect podman disk usage
  sos/report/plugins/podman.py
Labels: Reviewed/Ready for Merge, Kind/Collection

#4114 [block] Capture the /etc/crypttab file
  sos/report/plugins/block.py
Labels: Reviewed/Ready for Merge, Kind/Collection

#4119 [doc] Remove reference to legacy sosreport command
  README.md
Labels: Reviewed/Ready for Merge, Quick Change

#4131 [cirrus] Add debian-13 to test matrix
  .cirrus.yml
Labels: Status/Needs Review, Kind/Testing
