Repository sosreport/sos, pull requests merged in 2025-05, with the labels that each got.

#4000 [FedoraPolicy] Update sos binary path for collect
  sos/policies/distros/redhat.py
Labels: Kind/collect, Kind/Bug

#4005 [boot] add default kernel show
  sos/report/plugins/boot.py
Labels: Reviewed/Ready for Merge, Kind/Collection

#3974 [chrony] Capture chrony logs
  sos/report/plugins/chrony.py
Labels: Reviewed/Ready for Merge

#3987 [presets] Adjust OCP preset options
  sos/presets/redhat/__init__.py
Labels: Reviewed/Ready for Merge

#4008 [ceph_common]: Add New Microceph Commands
  sos/report/plugins/ceph_common.py
Labels: Reviewed/Ready for Merge

#4009 [ssh] Disable default listing of users's .ssh dirs
  sos/report/plugins/ssh.py
Labels: Reviewed/Ready for Merge

#4010 [cirrus] Update latest and dev release
  .cirrus.yml
Labels: Kind/Ubuntu, Reviewed/Ready for Merge, Kind/Testing

#4007 [fapolicyd] add more checks
  sos/report/plugins/fapolicyd.py
Labels: Reviewed/Ready for Merge, Kind/Collection

#4016 [sshd] Capture sshd -T
  sos/report/plugins/ssh.py
Labels: Status/Needs Review

#4015 [kdump] Capture vmcore-creation.status file
  sos/report/plugins/kdump.py
Labels: Status/Needs Review

#4012 [leapp] add version check
  sos/report/plugins/leapp.py
Labels: Reviewed/Ready for Merge, Kind/Good First Issue, Kind/Collection

#4018 [dnf] Scrub passwords in repository URIs
  sos/report/plugins/dnf.py
Labels: security, Reviewed/Ready for Merge, Quick Change, Kind/RedHat, Kind/Obfuscation

#4023 [leapp] collect /etc/leapp/files/dnf.conf
  sos/report/plugins/leapp.py
Labels: Reviewed/Ready for Merge

#4026 [cleaner] Use "hostname -f" in HostnamePrepper
  sos/cleaner/preppers/hostname.py
Labels: Reviewed/Ready for Merge, Kind/cleaner

#4011 [ovn_central,ovn_host] OVN Plugin Updates
  sos/report/plugins/ovn_central.py
  sos/report/plugins/ovn_host.py
Labels: Reviewed/Needs 2nd Ack, Status/Needs Review
