Repository sosreport/sos, pull requests merged in 2025-07, with the labels that each got.

#3833 [NetworkManager] Capture /var/run/NetworkManager folder
  sos/report/plugins/networkmanager.py
Labels: Reviewed/Ready for Merge

#4078 [kdump|release] Change format of imports
  sos/report/plugins/kdump.py
  sos/report/plugins/release.py
Labels: Reviewed/Ready for Merge, Quick Change

#4079 [subscription_manager] Obfuscate proxy env variables
  sos/report/plugins/subscription_manager.py
Labels: Reviewed/Ready for Merge

#4080 [upload] Avoid asking twice for case id
  sos/upload/targets/redhat.py
Labels: Reviewed/Ready for Merge, Quick Change, Kind/RedHat, Kind/Upload

#4083 [upload] Only load sos upload targets and not its policies
  sos/upload/__init__.py
Labels: Kind/Enhancement, Reviewed/Ready for Merge

#3988 [cleaner] Make cleaner concurrent inside one archive
  sos/cleaner/__init__.py
  sos/cleaner/archives/__init__.py
  sos/cleaner/archives/sos.py
  sos/cleaner/mappings/__init__.py
  sos/cleaner/mappings/ip_map.py
  sos/cleaner/mappings/ipv6_map.py
  sos/cleaner/mappings/mac_map.py
  sos/cleaner/parsers/__init__.py
  sos/cleaner/parsers/hostname_parser.py
  sos/cleaner/parsers/ip_parser.py
  sos/cleaner/parsers/ipv6_parser.py
  sos/cleaner/parsers/keyword_parser.py
  sos/cleaner/parsers/mac_parser.py
  sos/cleaner/parsers/username_parser.py
  tests/cleaner_tests/existing_archive.py
  tests/unittests/cleaner_tests.py
Labels: Kind/Enhancement, Reviewed/Ready for Merge, Kind/cleaner

#4091 [networking] Capture /etc/services file
  sos/report/plugins/networking.py
Labels: Reviewed/Ready for Merge

#4076 [openshift_ovn] Allow specific container runtime for plugin command
  sos/report/plugins/__init__.py
  sos/report/plugins/openshift_ovn.py
Labels: Kind/Enhancement, Kind/RedHat, Kind/Collection, Reviewed/Needs Rebase
