Repository sosreport/sos, pull requests merged in 2025-03, with the labels that each got.

#3951 [ceph_common] Obfuscate rgw password in ceph.conf
  sos/report/plugins/ceph_common.py
Labels: Status/Needs Review, Kind/Obfuscation, Kind/Bug

#3952 Include manager table in ovs captured data
  sos/report/plugins/openvswitch.py
Labels: Reviewed/Ready for Merge

#3949 [helm] Created new sos report plugin for Helm
  sos/report/plugins/helm.py
Labels: Reviewed/Needs 2nd Ack

#3954 Add .readthedocs.yaml to build correctly
  .readthedocs.yaml
Labels: Reviewed/Ready for Merge, Kind/Documentation, Kind/Bug

#3953 [ubuntu] Revamp of plugin
  sos/report/plugins/ubuntu.py
Labels: Kind/Ubuntu, Reviewed/Ready for Merge

#3957 [virsh] Update pkg trigger for Ubuntu/Debian
  sos/report/plugins/virsh.py
Labels: Kind/Ubuntu, Reviewed/Ready for Merge

#3955 [docs] Add upload and targets interface to docs
  .readthedocs.yaml
  README.md
  docs/index.rst
  docs/requirements.txt
  docs/targets.rst
  docs/upload.rst
  requirements.txt
  tox.ini
Labels: Reviewed/Ready for Merge, Kind/Documentation

#3958 [ubuntu] Add extra logs to be collected
  sos/report/plugins/ubuntu.py
Labels: Kind/Ubuntu, Reviewed/Ready for Merge

#3961 [clean] Update the last command for obfuscation
  sos/cleaner/preppers/usernames.py
Labels: security, Status/Needs Review, Kind/cleaner, Kind/Bug

#3963 [login,clean] Update login plugin and use for clean
  sos/cleaner/preppers/usernames.py
  sos/report/plugins/login.py
Labels: Reviewed/Ready for Merge

#3959 [cups] Expand captures in cups plugin
  sos/report/plugins/cups.py
Labels: Reviewed/Ready for Merge

#3966 [foreman] Add subnets table information
  sos/report/plugins/foreman.py
Labels: enhancement, Reviewed/Needs 2nd Ack, Kind/Collection

#3968 [report] Don't lowercase values by default
  sos/report/__init__.py
Labels: Reviewed/Ready for Merge, Kind/Bug

#3970 [charmed_mysql] Add Charmed MySQL support
  sos/report/plugins/charmed_mysql.py
Labels: Kind/Ubuntu, Reviewed/Ready for Merge
