Repository sosreport/sos, pull requests merged in 2025-02, with the labels that each got.

#3925 [ptp] Capture config files in /etc/sysconfig
  sos/report/plugins/ptp.py
Labels: Reviewed/Ready for Merge

#3746 [sos] Add 'upload' component to upload existing reports and files
  man/en/sos-upload.1
  setup.py
  sos/__init__.py
  sos/collector/__init__.py
  sos/help/__init__.py
  sos/policies/distros/__init__.py
  sos/policies/distros/redhat.py
  sos/policies/distros/ubuntu.py
  sos/report/__init__.py
  sos/upload/__init__.py
  sos/upload/targets/__init__.py
  sos/upload/targets/redhat.py
  sos/upload/targets/ubuntu.py
Labels: enhancement, Kind/Ubuntu, Status/Need More Info, Status/Canonical Eng, Status/RedHat Eng, Kind/RedHat

#3927 [openvswitch] Dump meter configuration and stats.
  sos/report/plugins/openvswitch.py
Labels: Reviewed/Ready for Merge

#3907 [testing] Add debian to standard testing
  .cirrus.yml
  debian/control
  tests/product_tests/foreman/foreman_tests.py
  tests/report_tests/plugin_tests/apt/apt.py
  tests/report_tests/plugin_tests/defaults.py
  tests/report_tests/plugin_tests/krb5.py
  tests/report_tests/smoke_tests.py
  tests/sos_tests.py
Labels: Status/Needs Review, Kind/Testing

#3932 [debian][pkg] Update to latest packaging config
  .cirrus.yml
  .gitignore
  debian/changelog
  debian/control
  debian/copyright
  debian/patches/0001-debian-change-tmp-dir-location.patch
  debian/patches/0002-debian-do-not-install-LICENSE-README-AUTHORS.patch
  debian/patches/series
  debian/rules
  debian/source/lintian-overrides
  debian/tests/control
  debian/tests/simple.sh
  debian/upstream/metadata
  debian/watch
Labels: Reviewed/Ready for Merge

#3934 Update FSF address in license text
  LICENSE
  sos/report/plugins/omnipath_client.py
  sos/report/plugins/omnipath_manager.py
Labels: Reviewed/Ready for Merge

#3936 [doc] lintian fix to reduce the line size
  README.md
Labels: Reviewed/Ready for Merge

#3935 [packaging] address fedora-review issues
  sos.spec
Labels: Reviewed/Ready for Merge

#3938 [component] Move _fmt_msg() to SoSComponent
  sos/cleaner/__init__.py
  sos/collector/__init__.py
  sos/component.py
  sos/upload/__init__.py
Labels: Reviewed/Needs 2nd Ack, Status/Needs Review

#3933 [docs] Remove nosetest details
  README.md
  tox.ini
Labels: Reviewed/Ready for Merge

#3944 [networking] List contents of netplan configuration dirs
  sos/report/plugins/networking.py
Labels: Kind/Ubuntu, Kind/Good First Issue, Status/Needs Review
